---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fmaovpetmf/gordonzhong.com/
    - export SERVERPATH=/home/fmaovpetmf/server/
    - /usr/bin/rsync -a --delete dist/. "$DEPLOYPATH"
    - /usr/bin/rsync -a --delete --exclude='node_modules' --exclude='.env' server/. "$SERVERPATH"
